# 空行追加
add_newline = true

# タイムアウト時間
scan_timeout = 10

# 記号の設定
#[character]
#success_symbol = "[>](bold green)" # コマンド成功時
#error_symbol = "[>](bold red)"    # コマンド失敗時

[character]
error_symbol = "[λ](bold #ff5555)"
success_symbol = "[λ](bold #f8f8f2)"

[cmd_duration]
style = "bold #f1fa8c"

[directory]
style = "bold #50fa7b"
truncation_length = 4
truncate_to_repo = false
truncation_symbol = '..…/'

[git_branch]
style = "bold #ff79c6"

[git_status]
style = "bold #ff5555"

[hostname]
style = "bold #ff5555"

[username]
format = "[$user]($style) on "
style_user = "bold #bd93f9"
